### ISSUE TITLE
Error when using function as type

### ISSUE THREAD

**Issue by CodeRiderz** [sobolevn/vue-flow-typed#24]
Flow removed the ability to use functions as type annotations in [v0.82.0](https://github.com/facebook/flow/releases/tag/v0.82.0) release.

So with the current definitions for function types, it will break.

**Comment by CodeRiderz** [comment]
Created PR for this #25

**Comment by sobolevn** [comment]
@CodeRiderz does it work for you now? Can you please verify with `master` branch?
If so, I will release a new version shortly.

**Comment by CodeRiderz** [comment]
@sobolevn --- Yes, it works for me with latest `flow-bin` (`0.89.0`)

**Comment by sobolevn** [comment]
@CodeRiderz thanks again. I have released a new version: `0.4.0`
